/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Barrage: typeof import('./src/components/Barrage.vue')['default']
    Camera: typeof import('./src/components/Camera.vue')['default']
    Danmu: typeof import('./src/components/Danmu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInpui: typeof import('element-plus/es')['ElInpui']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Flv: typeof import('./src/components/Flv.vue')['default']
    Meeting: typeof import('./src/components/Meeting.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/Screen.vue')['default']
    Socket: typeof import('./src/components/Socket.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
